import { NgModule } from '@angular/core';
//import so app can have routing capability
import { RouterModule, Routes } from '@angular/router';
import { HeroesComponent } from './heroes/heroes.component';
import {DashboardComponent} from "./dashboard/dashboard.component";
import {HeroDetailComponent} from "./hero-detail/hero-detail.component";

//generated by ng g m app-routing --flat --module=app
//--flat means to put it in app folder
//--module=app means to register it in app.module.ts

//this tell Router where to navigate when user clicks a link or paste URL
const routes: Routes = [
  { path: 'heroes', component: HeroesComponent },
  { path: 'dashboard', component: DashboardComponent },
  //added route to display hero details
  { path: 'detail/:id', component: HeroDetailComponent },
  { path: '', redirectTo: '/dashboard', pathMatch:"full" }
];

@NgModule({
  //configure module with all routes
  imports: [RouterModule.forRoot(routes)],
  //provide that Router is available throughout whole app
  exports: [RouterModule]
})

export class AppRoutingModule { }
