import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

//generated by ng g m app-routing --flat --module=app
//--flat means to put it in app folder
//--module=app means to register it in app.module.ts

@NgModule({
  declarations: [],
  imports: [
    CommonModule
  ]
})
export class AppRoutingModule { }
